### ISSUE TITLE
Carriage return and newline characters in dump

### ISSUE THREAD

**Issue by Siebe** [Podcastindex-org/docs-api#32] opened 2020-10-04 11:53 UTC
When I try to load the [CSV dump of the podcast](https://archive.org/details/podcastindex_dump) in to sqlite3 on Ubuntu, I still get a few faulty lines. These lines belong to the following podcasts:

https://api.podcastindex.org/api/1.0/podcasts/byfeedid?id=194753
https://api.podcastindex.org/api/1.0/podcasts/byfeedid?id=878138
https://api.podcastindex.org/api/1.0/podcasts/byfeedid?id=1081531

I'm sure it has something to do with /r and /n characters and might very have to do with the platform you're working out. On my linux machine it seems that I can find the conflicting lines by searching in vim for `/"\r\n[^\"]/`

This is also why CSV is not really the format to hold such rich content from so many sources. CSV is by default working with comma's, quotes and newlines. But the last is defined differently on different platforms. It's not imposslibe, but again @daveajones, I'd gently recommend to distribute a mysqldump generated sql file. This will also help importing the values as their correct types, instead having to parse everything from string :)

**Comment by saerdnaer** [comment] 2020-10-04 13:19
Duplicate of https://github.com/Podcastindex-org/database/issues/5 – basically currently the export contains both \n and \r\n as newlines. When trying to import, I also get UTF8 errors like `illegal byte sequence`:

```
wget https://archive.org/download/podcastindex_dump/podcasts_2020-10-02.csv

sed -e 's/"",/,/g'  podcasts_2020-10-02.csv > podcasts_2020-10-02_fixed.csv
> sed: RE error: illegal byte sequence

iconv -f UTF-8 podcasts_2020-10-02.csv > /dev/null                         
> iconv: podcasts_2020-10-02.csv:172436:66: cannot convert

```

**Comment by daveajones** [comment] 2020-10-04 14:04
I would gladly dump the table as a SQL file with mysqldump, but it contains the itunesOwnerEmail column, which I do not want to distribute. I can’t see a clean way to dump everything but that column without jumping through a bunch of temporary table hoops, which is time consuming on a table that large.  Maybe I’ll just bite the bullet and do it anyway.

**Comment by Siebe** [comment] 2020-10-04 21:10
There is indeed not really a way around doing a dump that way without temporary tables. But perhaps if you don't want to distribute that column, it should be in another place.

**Comment by saerdnaer** [comment] 2020-10-07 18:54
One could write an own exporter tool, which correctly writes the defined export format. I personally would prefer JSON or maybe even CSV. But we can also write a simple shell script with fixes the current export, e.g. by replacing all `/r/n` with `/n` and then all `/n` with `/r/n` again. But then we would still have the unicode errors...

**Comment by daveajones** [comment] 2020-10-08 01:10
Karsten in the mastadon shot me a python export tool he uses.  He said it should preserve the charset and do well.  I'm going to give that a shot this next time.

**Closed** 2020-10-28 13:02 UTC
